{% set version = "0.5.8" %}

package:
  name: crossplane
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/crossplane/crossplane-{{ version }}.tar.gz
  sha256: b193bd8b963a041d5414ea18dcbb1c55b5424fee3d73bfa1809124605b322101

build:
  entry_points:
    - crossplane = crossplane.__main__:main
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - crossplane
  commands:
    - pip check
    - crossplane --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/nginxinc/crossplane
  summary: Reliable and fast NGINX configuration file parser.
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - danielnachun
